# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='comment',
            name='timeago',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
